name: black

on: [push, pull_request]

jobs:
  black:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Check formatting with black
      run: |
        pip install black
        black --check .