name: black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with 
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install .
      - run: |
          black .