name: Tests

on: [push, pull_request]

jobs:
  latest:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install .

    - name: Check formatting with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        pytest --cov .

    - name: Upload coverage to Codecov
      # uses: codecov/codecov-action@v2
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}

    - name: Type checking with mypy
      run: |
        mypy  --ignore-missing-imports blobmodel

  python-3-10:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install .

    - name: Check formatting with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        pytest --cov .

    - name: Upload coverage to Codecov
      # uses: codecov/codecov-action@v2
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}

    - name: Type checking with mypy
      run: |
        mypy  --ignore-missing-imports blobmodel
