name: Tests

on: [push, pull_request]

jobs:
  latest:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install .

    - name: Check formatting with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        coverage run -m pytest
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        # env_vars: OS,PYTHON
        # fail_ci_if_error: true
        # files: ./coverage.xml,!./cache
        # name: codecov-umbrella
        # verbose: true

    - name: Type checking with mypy
      run: |
        mypy  --ignore-missing-imports blobmodel

  python-3-10:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install .

    - name: Check formatting with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        pytest --cov .

    - name: Type checking with mypy
      run: |
        mypy  --ignore-missing-imports blobmodel

  python-3-9:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install .

    - name: Check formatting with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        pytest --cov .

    - name: Type checking with mypy
      run: |
        mypy  --ignore-missing-imports blobmodel

  python-3-8:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install .

    - name: Check formatting with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        pytest --cov .

    - name: Type checking with mypy
      run: |
        mypy  --ignore-missing-imports blobmodel

  python-3-7:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install .

    - name: Check formatting with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        pytest --cov .

    - name: Type checking with mypy
      run: |
        mypy  --ignore-missing-imports blobmodel

  python-3-6:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v4
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        python -m pip install .

    - name: Check formatting with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        pytest --cov .

    - name: Type checking with mypy
      run: |
        mypy  --ignore-missing-imports blobmodel

  python-3-5:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.5
      uses: actions/setup-python@v4
      with:
        python-version: '3.5'

    - name: Install dependencies
      run: |
        python -m pip install .

    - name: Check formatting with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        pytest --cov .

    - name: Type checking with mypy
      run: |
        mypy  --ignore-missing-imports blobmodel
